---
- name: Solid-indexer install
  hosts: localhost
  gather_facts: False
  # remote_user: root
  vars_files:
    - ./vars/vars.yml

  tasks:
    - name: create system's directories for "{{ current_user}}"
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ current_user}}"
        # group: root
        mode: 0775
      become: true
      loop:
        - /opt/solid-indexer

    - name: create user's directories
      file:
        path: "{{ item }}"
        state: directory
        # owner: "{{ current_user}}"
        # group: root
        mode: 0775
      loop:
        - "{{ data_folder }}"

    - name: Create "{{root_folder}}/.env"
      ansible.builtin.template:
        src: ./templates/.env.j2
        dest: "{{root_folder}}/.env"
        force: no
        # owner: bin
        # group: wheel
        # mode: '0644'

    - name: Checkout a github repo and use refspec to fetch all pull requests
      ansible.builtin.git:
        repo: "https://github.com/scenaristeur/solid-indexer.git"
        dest: /opt/solid-indexer

    - name: Install requirements (might take a while)
      pip:
        requirements: /opt/solid-indexer/requirements.txt
        virtualenv: /opt/solid-indexer/.venv
        virtualenv_python: python3.10
      # verbosity: 0
